#!/bin/sh -x
# $Id: Check,v 1.1 2011-03-24 17:24:36-07 - - $
rm hello
pmake spotless    >spotless.log 2>&1
pmake ci          >ci.log 2>&1
pmake             >all.log 2>&1
rm hello
make spotless     >makespotless.log 2>&1
make ci           >makeci.log 2>&1
make              >makeall.log 2>&1
diff -y spotless.log makespotless.log
diff -y ci.log makeci.log
diff -y all.log makeall.log
